"""Tests for engagement create bootstrap provisioning.

Verifies the full three-artifact bootstrap:
  1. DB row created with pre-generated engagement_id
  2. On-disk engagement directory provisioned via ArtifactManager
  3. Config snapshot mirrored to filesystem

And rollback invariants:
  - Dir provision failure -> DB row deleted
  - update_engagement_dir failure -> dir removed + DB row deleted
  - Mirror failure -> dir removed + DB row deleted
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock, patch

import yaml
from click.testing import CliRunner

from gxassessms.cli.main import cli

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _write_config(tmp_path: Path) -> Path:
    """Write a minimal valid config YAML and return its path."""
    config_path = tmp_path / "config.yaml"
    config_data = {
        "client": {
            "name": "Test Corp",
            "tenant_id": "00000000-0000-0000-0000-000000000001",
        },
        "auth": {
            "method": "client_credential",
            "tenant_id": "00000000-0000-0000-0000-000000000001",
            "client_id": "00000000-0000-0000-0000-000000000002",
            "client_secret_env": "GX_SECRET",  # pragma: allowlist secret
        },
        "tools": {
            "scubagear": True,
        },
    }
    config_path.write_text(yaml.dump(config_data), encoding="utf-8")
    return config_path


def _make_mock_repo(engagement_id: str = "eng-bootstrap-001") -> MagicMock:
    """Return a mock EngagementRepo whose create() echoes back the engagement_id kwarg.

    The engagement_id is pre-generated by the CLI and passed in; create() returns it
    unchanged. The engagement_id parameter here is kept for API compatibility but is
    no longer used as a fixed return value.
    """
    repo = MagicMock()
    repo.create.side_effect = lambda **kwargs: kwargs.get("engagement_id", engagement_id)
    return repo


def _make_mock_artifacts(eng_dir: Path | None = None) -> MagicMock:
    """Return a mock ArtifactManager whose create_engagement_dir() returns eng_dir."""
    artifacts = MagicMock()
    if eng_dir is not None:
        artifacts.create_engagement_dir.return_value = eng_dir
    return artifacts


# ---------------------------------------------------------------------------
# Happy path
# ---------------------------------------------------------------------------


class TestEngagementCreateBootstrapHappyPath:
    """All three artifacts created; verify each call is made."""

    @patch(
        "gxassessms.pipeline.config_snapshot_mirror.mirror_config_snapshot_from_db_strict",
        autospec=True,
    )
    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_happy_path_creates_db_row(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        mock_mirror: MagicMock,
        tmp_path: Path,
    ) -> None:
        """repo.create() is called once with client_name, tenant_id, and snapshot."""
        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-001"
        eng_dir.mkdir()
        mock_get_repo.return_value = _make_mock_repo("eng-001")
        mock_get_artifacts.return_value = _make_mock_artifacts(eng_dir)

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code == 0, result.output
        mock_get_repo.return_value.create.assert_called_once()
        call_kwargs = mock_get_repo.return_value.create.call_args.kwargs
        assert call_kwargs["client_name"] == "Test Corp"
        assert call_kwargs["tenant_id"] == "00000000-0000-0000-0000-000000000001"
        assert "config_snapshot" in call_kwargs
        assert "engagement_id" in call_kwargs

    @patch(
        "gxassessms.pipeline.config_snapshot_mirror.mirror_config_snapshot_from_db_strict",
        autospec=True,
    )
    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_happy_path_provisions_directory(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        mock_mirror: MagicMock,
        tmp_path: Path,
    ) -> None:
        """create_engagement_dir() is called with engagement_id and client_name."""
        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-002"
        eng_dir.mkdir()
        mock_repo = _make_mock_repo("eng-002")
        mock_get_repo.return_value = mock_repo
        mock_artifacts = _make_mock_artifacts(eng_dir)
        mock_get_artifacts.return_value = mock_artifacts

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code == 0, result.output
        mock_artifacts.create_engagement_dir.assert_called_once()
        create_dir_args = mock_artifacts.create_engagement_dir.call_args
        actual_id = mock_repo.create.call_args.kwargs["engagement_id"]
        assert actual_id in create_dir_args.args or (
            create_dir_args.kwargs.get("engagement_id") == actual_id
        )

    @patch(
        "gxassessms.pipeline.config_snapshot_mirror.mirror_config_snapshot_from_db_strict",
        autospec=True,
    )
    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_happy_path_calls_mirror(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        mock_mirror: MagicMock,
        tmp_path: Path,
    ) -> None:
        """mirror_config_snapshot_from_db_strict() is called with repo, artifacts, eid."""
        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-003"
        eng_dir.mkdir()
        mock_repo = _make_mock_repo("eng-003")
        mock_get_repo.return_value = mock_repo
        mock_artifacts = _make_mock_artifacts(eng_dir)
        mock_get_artifacts.return_value = mock_artifacts

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code == 0, result.output
        actual_id = mock_repo.create.call_args.kwargs["engagement_id"]
        mock_mirror.assert_called_once_with(mock_repo, mock_artifacts, actual_id)

    @patch(
        "gxassessms.pipeline.config_snapshot_mirror.mirror_config_snapshot_from_db_strict",
        autospec=True,
    )
    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_happy_path_updates_engagement_dir(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        mock_mirror: MagicMock,
        tmp_path: Path,
    ) -> None:
        """repo.update_engagement_dir() is called with the provisioned path."""
        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-004"
        eng_dir.mkdir()
        mock_repo = _make_mock_repo("eng-004")
        mock_get_repo.return_value = mock_repo
        mock_artifacts = _make_mock_artifacts(eng_dir)
        mock_get_artifacts.return_value = mock_artifacts

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code == 0, result.output
        actual_id = mock_repo.create.call_args.kwargs["engagement_id"]
        mock_repo.update_engagement_dir.assert_called_once_with(
            actual_id, engagement_dir=str(eng_dir)
        )

    @patch(
        "gxassessms.pipeline.config_snapshot_mirror.mirror_config_snapshot_from_db_strict",
        autospec=True,
    )
    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_happy_path_success_output(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        mock_mirror: MagicMock,
        tmp_path: Path,
    ) -> None:
        """Successful create prints the engagement ID."""
        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-005"
        eng_dir.mkdir()
        mock_get_repo.return_value = _make_mock_repo("eng-005")
        mock_get_artifacts.return_value = _make_mock_artifacts(eng_dir)

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code == 0, result.output
        actual_id = mock_get_repo.return_value.create.call_args.kwargs["engagement_id"]
        assert "created" in result.output.lower()
        assert actual_id in result.output


# ---------------------------------------------------------------------------
# Rollback: directory provision failure
# ---------------------------------------------------------------------------


class TestEngagementCreateDirProvisionRollback:
    """create_engagement_dir failure -> DB row deleted, exit nonzero."""

    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_dir_failure_deletes_db_row(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        tmp_path: Path,
    ) -> None:
        """When create_engagement_dir raises, repo.delete(eid) is called."""
        config_path = _write_config(tmp_path)
        mock_repo = _make_mock_repo("eng-rollback-dir")
        mock_get_repo.return_value = mock_repo
        mock_artifacts = MagicMock()
        mock_artifacts.create_engagement_dir.side_effect = OSError("disk full")
        mock_get_artifacts.return_value = mock_artifacts

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code != 0
        actual_id = mock_repo.create.call_args.kwargs["engagement_id"]
        mock_repo.delete.assert_called_once_with(actual_id)

    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_dir_failure_exits_nonzero(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        tmp_path: Path,
    ) -> None:
        """When create_engagement_dir raises, exit code is nonzero."""
        config_path = _write_config(tmp_path)
        mock_get_repo.return_value = _make_mock_repo("eng-rollback-dir-exit")
        mock_artifacts = MagicMock()
        mock_artifacts.create_engagement_dir.side_effect = OSError("disk full")
        mock_get_artifacts.return_value = mock_artifacts

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code != 0

    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_dir_failure_rollback_delete_failure_does_not_reraise(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        tmp_path: Path,
    ) -> None:
        """If rollback delete itself raises, it is swallowed (best-effort)."""
        from gxassessms.core.contracts.errors import PersistenceError

        config_path = _write_config(tmp_path)
        mock_repo = _make_mock_repo("eng-rollback-del-fail")
        mock_repo.delete.side_effect = PersistenceError("gone already")
        mock_get_repo.return_value = mock_repo
        mock_artifacts = MagicMock()
        mock_artifacts.create_engagement_dir.side_effect = OSError("disk full")
        mock_get_artifacts.return_value = mock_artifacts

        runner = CliRunner()
        # Should not raise -- just exit nonzero
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])
        assert result.exit_code != 0


# ---------------------------------------------------------------------------
# Rollback: update_engagement_dir failure
# ---------------------------------------------------------------------------


class TestEngagementCreateUpdateDirRollback:
    """update_engagement_dir failure -> dir removed + DB row deleted, exit nonzero."""

    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_update_dir_failure_removes_dir_and_deletes_row(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        tmp_path: Path,
    ) -> None:
        """When update_engagement_dir raises, shutil.rmtree and repo.delete are called."""
        from gxassessms.core.contracts.errors import PersistenceError

        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-upd"
        eng_dir.mkdir()
        mock_repo = _make_mock_repo("eng-upd-rollback")
        mock_repo.update_engagement_dir.side_effect = PersistenceError("update failed")
        mock_get_repo.return_value = mock_repo
        mock_artifacts = _make_mock_artifacts(eng_dir)
        mock_get_artifacts.return_value = mock_artifacts

        with patch("shutil.rmtree") as mock_rmtree:
            runner = CliRunner()
            result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code != 0
        mock_rmtree.assert_called_once_with(eng_dir, ignore_errors=True)
        actual_id = mock_repo.create.call_args.kwargs["engagement_id"]
        mock_repo.delete.assert_called_once_with(actual_id)


# ---------------------------------------------------------------------------
# Rollback: mirror failure
# ---------------------------------------------------------------------------


class TestEngagementCreateMirrorRollback:
    """Mirror failure -> dir removed + DB row deleted, exit nonzero."""

    @patch(
        "gxassessms.pipeline.config_snapshot_mirror.mirror_config_snapshot_from_db_strict",
        autospec=True,
    )
    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_mirror_failure_removes_dir_and_deletes_row(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        mock_mirror: MagicMock,
        tmp_path: Path,
    ) -> None:
        """When mirror raises, shutil.rmtree and repo.delete are called."""
        from gxassessms.core.contracts.errors import ConfigSnapshotMirrorError

        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-mirror"
        eng_dir.mkdir()
        mock_repo = _make_mock_repo("eng-mirror-rollback")
        mock_get_repo.return_value = mock_repo
        mock_artifacts = _make_mock_artifacts(eng_dir)
        mock_get_artifacts.return_value = mock_artifacts
        mock_mirror.side_effect = ConfigSnapshotMirrorError(
            "write failed", engagement_id="eng-mirror-rollback"
        )

        with patch("shutil.rmtree") as mock_rmtree:
            runner = CliRunner()
            result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code != 0
        mock_rmtree.assert_called_once_with(eng_dir, ignore_errors=True)
        actual_id = mock_repo.create.call_args.kwargs["engagement_id"]
        mock_repo.delete.assert_called_once_with(actual_id)

    @patch(
        "gxassessms.pipeline.config_snapshot_mirror.mirror_config_snapshot_from_db_strict",
        autospec=True,
    )
    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_mirror_failure_exits_nonzero(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        mock_mirror: MagicMock,
        tmp_path: Path,
    ) -> None:
        """Mirror failure exits nonzero."""
        from gxassessms.core.contracts.errors import ConfigSnapshotMirrorError

        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-mirror-exit"
        eng_dir.mkdir()
        mock_get_repo.return_value = _make_mock_repo("eng-mirror-exit")
        mock_get_artifacts.return_value = _make_mock_artifacts(eng_dir)
        mock_mirror.side_effect = ConfigSnapshotMirrorError(
            "write failed", engagement_id="eng-mirror-exit"
        )

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])

        assert result.exit_code != 0

    @patch(
        "gxassessms.pipeline.config_snapshot_mirror.mirror_config_snapshot_from_db_strict",
        autospec=True,
    )
    @patch("gxassessms.cli._helpers.get_artifact_manager", autospec=True)
    @patch("gxassessms.cli._helpers.get_engagement_repo", autospec=True)
    def test_mirror_failure_rollback_delete_failure_does_not_reraise(
        self,
        mock_get_repo: MagicMock,
        mock_get_artifacts: MagicMock,
        mock_mirror: MagicMock,
        tmp_path: Path,
    ) -> None:
        """If rollback delete raises during mirror failure, it is swallowed."""
        from gxassessms.core.contracts.errors import (
            ConfigSnapshotMirrorError,
            PersistenceError,
        )

        config_path = _write_config(tmp_path)
        eng_dir = tmp_path / "test-corp-eng-mirror-del-fail"
        eng_dir.mkdir()
        mock_repo = _make_mock_repo("eng-mirror-del-fail")
        mock_repo.delete.side_effect = PersistenceError("already gone")
        mock_get_repo.return_value = mock_repo
        mock_get_artifacts.return_value = _make_mock_artifacts(eng_dir)
        mock_mirror.side_effect = ConfigSnapshotMirrorError(
            "write failed", engagement_id="eng-mirror-del-fail"
        )

        runner = CliRunner()
        result = runner.invoke(cli, ["engagement", "create", str(config_path)])
        assert result.exit_code != 0
